# Secrets can't be read across namespaces, so payment gets its own copy
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-client-credentials
  namespace: payment
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
