# Copy of RMQ creds in the checkout namespace
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-client-credentials
  namespace: checkout
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.pass | b64enc }}
