# Copy of RMQ creds in the payment namespace (Secrets don't cross namespaces)
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-client-credentials
  namespace: payment
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.pass | b64enc }}
