# RMQ creds copied into the payment namespace for spring-boot to consume
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-client-credentials
  namespace: payment
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.pass | b64enc }}
